services:
  server:
    image: afrima/e-book-manager:dev
    restart: on-failure
    ports:
      - "443:8080"
    environment:
      GIN_MODE: "release"
      dbPassword: "super-secret"
      dbUser: "postgres"
      dbAddress: "db"
      dbPort: "5432"
      dbName: "ebooks"
    volumes:
      - book-data:/home/appuser/upload/
    depends_on:
      - "db"
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "super-secret"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ebooks"
    ports:
      - "5432:5432"
    volumes:
      - book-db:/var/lib/postgresql/data

volumes:
  book-data:
    external: false
  book-db:
    external: false
