name: Build

on:
  pull_request:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  dry_release:
    name: dry release
    uses: mathieu-keller/github-action-workflows/.github/workflows/semantic-release.yaml@2.0.1
    with:
      release-branch: main
      dry: true
  version-echo:
    runs-on: ubuntu-24.04
    needs: [ dry_release ]
    steps:
      - name: echo
        run: echo ${{ needs.dry_release.outputs.new_version }}
  test:
    name: go test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: install dep
        run: |
          go get -v
      - name: test
        run: go test -v ./...
  build_service:
    name: build service
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Set up
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: install dep
        run: |
          go get -v
      - name: build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: src/e-book-manager
  docker:
    name: build docker
    runs-on: ubuntu-24.04
    needs: [ test, build_service, dry_release ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ./docker
      - name: Copy sql
        run: |
          cp -R ./src/sql ./docker/sql
      - name: Build image
        working-directory: ./docker
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/e-book-manager
      - name: push image
        run: |
          docker login -u=${{ secrets.DOCKER_USER }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_USER }}/e-book-manager ${{ secrets.DOCKER_USER }}/e-book-manager:${{ needs.dry_release.outputs.new_version }}
          docker push ${{ secrets.DOCKER_USER }}/e-book-manager:${{ needs.dry_release.outputs.new_version }}
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: src
  release:
    name: create release
    needs: [ docker ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: mathieu-keller/github-action-workflows/.github/workflows/semantic-release.yaml@2.0.1
    with:
      release-branch: main
      dry: false